version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo hello hello
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t phlw-todo:latest .
      - docker tag phlw-todo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/phlw-c2:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/phlw-c2:latest
      - printf '[{"name":"phlw-todo","imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/phlw-c2:latest"}]' > imagedefinitions.json
  artifacts:
    files: imagedefinitions.json

